version: '3'
services:
  birthday-service:
    image: birthday-service
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_SERVER: mongo-server:27017
      DB_NAME: birthdayDB
    depends_on:
      - mongo-server
      - user-service
  mongo-server:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
  user-service:
    image: 'user-service:latest'
    ports:
      - '8086:8080'
